#
# Default settings for monitor
#

# Object IDs
object_ids:
  - resttranslator:Default.png
  - systemmanager:Default.png
  - romgr1:Default.png
  - gen:Default.png
  - network1:Network.png
  - aggre:Default.png
  - network0:Network.png
  - lsw:Default.png
